import 'package:http/http.dart' as http;
import 'package:new_design_news_app/model/news_model.dart';
import 'package:new_design_news_app/model/category_model.dart';
import 'package:new_design_news_app/model/user_model.dart';

class APIService {
  static var client = http.Client();

  static Future<List<Autogenerated>?> categories() async {
    var response = await client.get(
        Uri.parse(
            'https://nepalsansar.com/wp-json/wp/v2/categories?per_page=100'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        });
    if (response.statusCode == 200) {
      var jsonString = response.body;
      return categoryPostFromJson(jsonString);
    } else {
      return null;
    }
  }

  static Future<List<News>?> news(int pageNumber, int catId) async {
    var response = await client.get(
        Uri.parse(
            'https://nepalsansar.com//wp-json/wp/v2/posts?per_page=10&order_date=desc&page=$pageNumber&categories=$catId'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        });

    if (response.statusCode == 200) {
      var jsonString = response.body;
      return postFromJson(jsonString);
    } else {
      return null;
    }
  }

  static Future<List<News>?> drawerNews(
    int drawerPageNumber,
    int drawercatId,
  ) async {
    var response = await client.get(
        Uri.parse(
            'https://nepalsansar.com//wp-json/wp/v2/posts?per_page=10&order_date=desc&page=$drawerPageNumber&categories=$drawercatId'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        });

    if (response.statusCode == 200) {
      var jsonString = response.body;
      return postFromJson(jsonString);
    } else {
      return null;
    }
  }

  static Future<User?> fetchUser(int userId) async {
    var response = await client.get(
        Uri.parse('https://nepalsansar.com//wp-json/wp/v2/users/$userId'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        });
    if (response.statusCode == 200) {
      var jsonString = response.body;
      return userFromJson(jsonString);
    } else {
      return null;
    }
  }
}
