import 'package:get/get.dart';
import 'package:new_design_news_app/model/category_model.dart';
import 'package:new_design_news_app/service/api_service.dart';

class CategoriesController extends GetxController {
  
  var isLoading = true.obs;
  var categoriesList = <Autogenerated>[].obs;

  @override
  void onInit() {
    fetchCategories();
    super.onInit();
  }

  Future<void> fetchCategories() async {
    try {
      isLoading(true);
      var categories = await APIService.categories();
      if (categories!.length > 0) {
        categoriesList.clear();
        categoriesList.addAll(categories);
      }
    } finally {
      isLoading(false);
    }
  }
}
